import React from "react";

const Terms = () => {
    
    return(
        <div className="terms">
            <span>Terms and Conditions</span>
            <p>
                Last updated: July 20, 2022        
                <br>
                </br>
                Please read these terms and conditions carefully before using the Website.
            </p>
            <br>
            </br>
            <span>Introduction</span>
            <p>
                ∆FLORA Genesis (each a “∆FLORA” and collectively the “∆FLORA Genesis”) is a collection of digital collectibles or non-fungible tokens (each, an “NFT”, and in plurality, the “NFTs”) utilizing blockchain technologies on the Ethereum Network. The Website is only an interface allowing Users to transact and interact with the NFTs. Users are entirely responsible for the safety and management of their own
                cryptocurrency wallets and in validating all Transactions generated by the Website before User's approval. Users expressly acknowledge that there is no ability to undo, reverse, or restore any such Transactions. The Website, our smart contracts, and all services related to the ∆FLORA Genesis collection are provided to Users “as is” without any warranty or promise of availability of services of any kind. By using the Website, minting the NFTs, or interacting with our smart contracts, Users are accepting and assuming sole responsibility for any and all Transactions involving the NFTs and any other collectibles relating to the ∆FLORA Genesis collection. These
                Terms are meant to cover any ∆FLORA Genesis Collection which exists in the SACRED GARDEN universe.
            </p>
            <br>
            </br>
            <span>DEFINITIONS</span>
            <p>
                For the purposes of these Terms, the following definitions shall have the same meaning regardless of whether they appear in singular or in plural:
                “Affiliate” means the respective shareholders, directors, officers, employees, affiliates, agents, representatives, licensors, suppliers, members or service providers of Company or Users.
                “Art” means the underlying copyright of any individual NFT.
                “Country” means the United States of America.
                “Company” (referred to as either “Company”, “we”, “us” or “our” in these Terms) refers to GARDN LLC, located at 651 North Broad Street, Suite 206, Middletown, Delaware 19709.
                “Device” means any internet-capable apparatuses, machines, appliances, and hardware, now known or hereinafter devised and/or created, regardless of the particular underlying technology and mechanism and manner of connection, including, but not limited to, so-called “Smart TVs,” computers, laptops, desktops, tablets, iPads, and mobile phones.
                “Ethereum Network” means the blockchain powered by Ethereum.
                “License” has the meaning set out in these Terms.
                “Polygon Network” means the blockchain powered by Polygon.
                “Services” means all communications, functionality, features, arrangements, organization, codes, software, opportunities, interactions, and activities made available on or through the Website.
                “Terms and Conditions” (also referred as “Terms”) mean these Terms that form the entire agreement (“Agreement”) between Company and Users regarding the use of the Website.
                “Third-Party Providers” means any individuals, entities, services, manufacturers, organizations, contributors, or marketplaces involved with or connected to any Transaction.
                “Transaction(s)” means any and all aspects of Users’ purchase and/or interactions with NFTs on and/or through the Website and/or any Third-Party Providers.
                “User(s)”, “you”, or “your” means any individual or Affiliate accessing the Website.
                “Website” means the URL www.sacrdgardn.com
            </p>
            <br>
            </br>
            <span>ACKNOWLEDGMENT:</span>
            <p>
                By accessing and using the Website, User represents, warrants, covenants, and affirms that User:
                (i) has read, comprehends, and agrees to be bound and to abide by these Terms; (ii) is eighteen (18) years or older; and (iii) is solely responsible for ensuring that all others who use or otherwise access the Website satisfy the requirements set forth in these Terms at all times. If User does not satisfy the foregoing requirements, adherence to these Terms, including, any subsequent modifications, updates, or alterations to any of the foregoing, User is required, and hereby agrees, to immediately cease and discontinue any access to and use of the Website.
            </p>
            <br>
            </br>
            <span>INTELLECTUAL PROPERTY:</span>
            <p>
                User hereby acknowledges and understands that all Transactions are mediated entirely by smart contracts and the Ethereum Network, outside of the control of Company and any of Company’s Affiliates. At no point may Company seize, freeze, or otherwise modify the ownership of any NFTs. NFTs may contain Company’s branding, trademarks and/or other intellectual property owned and created by Company (collectively, the “Branding”). User hereby acknowledges and agrees that all Branding remains the sole and exclusive property of and wholly owned by Company and such Branding shall not be transferred to Users in connection with any Transactions. User has
                no right to use any of the Branding in connection with the sale of any commercial product. Provided that you do not make use of the Art for any illicit or illegal purpose, Company hereby grants you a worldwide, non-exclusive, royalty-free right and license (the “License”) to use,
                copy, and display the NFT and the underlying Art, together with any extensions thereof that you choose to create or use, in any media now known or hereinafter devised or created, solely:
            <ul>
                <li>for personal use: for your own personal, non-commercial use;</li>
                <li>for commercial use: for creating derivative works for commercial based upon the Art, such as using the Art in connection with various creative works and/or products, including, but not limited to, film, television, animated productions, video games, endorsements, designs, products, merchandising and any other creative activities, which display or represent copies of the Art (each, a “Derivative Work”); and</li>
                <li>
                    as part of a marketplace, third-party website or application (each, a “Platform”) that permits any Transaction or display of any NFT, provided that the Platform verifies on the blockchain each NFT-owner’s rights to such Transaction or display in order to ensure
                    that only the actual owner can approve such Transaction or display such NFT, and provided further that the NFT is no longer visible once removed from the Platform.
                </li>
            </ul>
            Except for the License, Company and its Affiliates retain all right, title, and interest in and to the Branding and Art and is at all times permitted to make use of the Art for the following purposes:
            <ul>
                <li>for creating Derivative Works for commercial and non-commercial purposes; and</li>
                <li>
                    as part of a Platform that permits any Transaction or display of any NFT, provided that the Platform verifies on the blockchain each NFT-owner’s rights to such Transaction or display to ensure that only the actual owner can approve such Transaction or display such
                    NFT, and provided further the NFT is no longer visible once removed from the Platform. In the event that Company enters into an agreement with any third-party in which Company desires to grant exclusivity in connection with any Derivative Work, your rights relating to such Derivative Work shall immediately terminate and you shall cease exploitation thereof and, to the extent possible, you agree to use best efforts to cause any third-party to which you have granted
                    such rights to promptly cease exploitation and terminate any agreements entered into.
                </li>
            </ul>
            </p>
            <br>
            </br>
            <span>TRANSACTIONS VIA THIRD PARTY PROVIDERS:</span>
            <p>
                Users understand and agree that any Transaction of an NFT will be, at all times, subject to any third-party rights that may be transferred by any previous owners and/or Affiliates of such NFT. For the avoidance of doubt, Users understand and agree to be bound by any and all preexisting grants and/or assignments that may be attached to any such NFT.
            </p>
            <br>
            </br>
            <span>LINKS TO OTHER WEBSITES:</span>
            <p>
                The Website and/or the Services may contain links to third-party websites or services that are not owned or controlled by Company. User hereby acknowledges that Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services. User further acknowledges that Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such websites or services. Company strongly advises that User reads the terms of
                service and privacy policies of any third-party websites or services that User visits.
            </p>
            <br>
            </br>
            <span>TERMINATION:</span>
            <p>
                We may immediately terminate or suspend your access to the Website, without prior notice or liability, for any reason whatsoever, including, but not limited to, if you breach these Terms. Upon such termination, your right to use the Website and/or the Services will cease immediately.
            </p>

            <br>
            </br>

            <span>LIMITATION OF LIABILITY:</span>
            <p>
                Notwithstanding any damages that you may incur, the entire liability of Company and its Affiliates under any provision of these Terms and your exclusive remedy for all of the foregoing shall be limited to the greater of the amount actually paid by you in connection with the Services or one hundred dollars ($100). To the maximum extent permitted by applicable law, in no event shall Company or its Affiliates be liable for any special, incidental, indirect, or consequential
                damages whatsoever (including, damages for loss of profits, loss of data or other information, for business interruption, for personal injury, loss of privacy arising out of or in any way related to the use of or inability to use the Services, third-party software and/or third-party hardware used with the Services, loss of any gas fees for failed Transactions, any excessive gas fees charged due to Website or smart contract bugs, any loss of any NFT due to Website or smart contract bugs, loss of assets from your wallet, or otherwise in connection with any provision of these Terms), even if Company or its Affiliates has been advised of the possibility of such damages and even if the remedy fails of its essential purpose. Some states do not allow the exclusion of implied warranties or limitation of liability for incidental or consequential damages, which means that some of the above limitations may not apply. In such states, each party’s liability
                will be limited to the greatest extent permitted by law. Neither Company nor its Affiliates makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the Website and/or Services, or the information, content, and materials or products included thereon; (ii) that the Website and/or Services will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the Website and/or Services; or (iv) that the Website and/or Services,
                its servers, the Transactions, or communications sent from or on behalf of Company are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components. Some jurisdictions do not allow the exclusion of certain types of warranties or limitations on applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply; but in such a case the exclusions and limitations set forth in this section shall be applied to
                the greatest extent enforceable under applicable law.
            </p>

            <br>
            </br>

            <span>NO GUARANTEE OR PROMISES OF FUTURE SERVICES:</span>
            <p>
                NO GUARANTEE OR PROMISES OF FUTURE SERVICES:
                We are fully committed to the ∆FLORA Genesis Collection and hope to continually grow and develop the SACRED GARDEN and community. Our roadmap details the objectives that we hope to achieve in growing our collection. While our goal is to fulfill the roadmap, sometimes things happen and, as such, we cannot make any guarantees as to the success of the collection nor can we guarantee any further developments of the collection. By conducting a Transaction hereunder, you agree that you are not relying on any future commitments by any of the SACRED GARDEN team. By conducting Transactions on the Website or via Third-Party Providers, you agree that the NFT is not meant to be an investment. We make no claims or guarantees that your NFT is or will be worth anything. You understand that your NFT has no inherent monetary value, and any such NFT should be treated as nothing more than a fun collectible. Additionally, there should be no expectation that your NFT will create any ancillary value whether monetary or otherwise. You are entirely responsible for any tax liability which may arise from conducting any Transaction.
            </p>

            <br>
            </br>

            <span>GOVERNING LAW:</span>
            <p>
                The laws of the Country, excluding its conflicts of law rules, shall govern these Terms.
            </p>

            <br>
            </br>

            <span>DISPUTE RESOLUTION:</span>
            <p>
                If you have any concern or dispute about the Website and/or the Services, you agree to first try to resolve the dispute informally by contacting Company at the email address below.
            </p>

            <br>
            </br>

            <span>FOR EUROPEAN UNION USERS:</span>
            <p>
                If you reside in the European Union, you will benefit from any mandatory provisions of the law of the country in which you are a resident in connection with use of the Website and/or Services.
            </p>

            <br>
            </br>

            <span>SEVERABILITY:</span>
            <p>
                If any provision of these Terms is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.    
            </p>

            <br>
            </br>

            <span>WAIVER:</span>
            <p>
                Except as provided herein, the failure to exercise a right or to require performance of an obligation under these Terms shall not affect a party’s ability to exercise such right or require such performance at any time thereafter, nor shall the waiver of a breach constitute a waiver of any subsequent breach. You agree to waive any class action status, and any legal dispute around the ∆FLORA Genesis Collection which you may bring, shall only be done on an individual basis.
            </p>
            
            <br>
            </br>

            <span>CHANGES TO THESE TERMS AND CONDITIONS:</span>
            <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will make reasonable efforts to provide at least thirty (30) days’ notice to you prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use the Website and/or the Services after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to
                the new terms, in whole or in part, please stop using the Website and/or the Services.
                Contact Us:
                If you have any questions about these Terms, you can contact us: hi@sacrdgardn.com
            </p>
        </div>
    
    )
}

export default Terms